"""empty message

Revision ID: 094e1f1b74c1
Revises: 2565c1413bdc
Create Date: 2024-05-16 11:31:43.371680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094e1f1b74c1'
down_revision = '2565c1413bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criação', sa.DateTime(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
