"""empty message

Revision ID: 1face908ef1e
Revises: 094e1f1b74c1
Create Date: 2024-05-21 10:50:55.293468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1face908ef1e'
down_revision = '094e1f1b74c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classe_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criação', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classe_comentario')
    # ### end Alembic commands ###
