"""empty message

Revision ID: d15caec739bb
Revises: 1face908ef1e
Create Date: 2024-06-11 11:54:25.398249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15caec739bb'
down_revision = '1face908ef1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classe_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useriddoparaguai', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classe_comentario', schema=None) as batch_op:
        batch_op.drop_column('useriddoparaguai')

    # ### end Alembic commands ###
